### ISSUE TITLE
running in dev mode still looking for GOOGLE_APPLICATION_CREDENTIALS

### ISSUE THREAD

**Issue by xmlking** [jamesward/spring-kotlin-postgres#1]
are there any tricks  to disable  `spring cloud gcp` during development(`gradle bootRun`) ?
I have this in `application-production.yml` 
```yaml 
spring.cloud.gcp.core.enabled: true
spring.cloud.gcp.metrics.enabled: true
management.metrics.export.stackdriver.enabled: true
management.metrics.export.stackdriver.step: 5s

```

[2021-11-22 10:01:14.093] - 96779 SEVERE [restartedMain] --- io.micrometer.stackdriver.StackdriverMeterRegistry: unable to create stackdriver client
java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
        at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:134)
        at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:125)
        at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:97)
        at com.google.api.gax.core.GoogleCredentialsProvider.getCredentials(GoogleCredentialsProvider.java:70)
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:172)
        at com.google.cloud.monitoring.v3.stub.GrpcMetricServiceStub.create(GrpcMetricServiceStub.java:191)
        at com.google.cloud.monitoring.v3.stub.MetricServiceStubSettings.createStub(MetricServiceStubSettings.java:402)
        at com.google.cloud.monitoring.v3.MetricServiceClient.<init>(MetricServiceClient.java:156)
        at com.google.cloud.monitoring.v3.MetricServiceClient.create(MetricServiceClient.java:137)
        at io.micrometer.stackdriver.StackdriverMeterRegistry.start(StackdriverMeterRegistry.java:123)
        at io.micrometer.stackdriver.StackdriverMeterRegistry.<init>(StackdriverMeterRegistry.java:109)
        at io.micrometer.stackdriver.StackdriverMeterRegistry.<init>(StackdriverMeterRegistry.java:65)
        at io.micrometer.stackdriver.StackdriverMeterRegistry$Builder.build(StackdriverMeterRegistry.java:294)
        at com.google.cloud.spring.autoconfigure.metrics.GcpStackdriverMetricsAutoConfiguration.stackdriverMeterRegistry(GcpStackdriverMetricsAutoConfiguration.java:94)

**Comment by xmlking** [comment]
Got this workaround 


add following to `application.yml`
```
spring.cloud.gcp.core.enabled: false
management.metrics.export.stackdriver.enabled: false
```

https://github.com/micrometer-metrics/micrometer/issues/2870

**Comment by jamesward** [comment]
Did you run into this issue with this repo (exactly as it is)?  Cause it should work out-of-the-box.  The `src/test/resources/application.properties` combined with adding the `test` sources classpath to `bootRun` in Gradle should set those.  You'll also need to make sure you don't have a `src/main/resources/application.properties` because in that case the `test` one doesn't get picked up.

**Comment by jamesward** [comment]
Did you run into this issue with this repo (exactly as it is)?  Cause it should work out-of-the-box.  The `src/test/resources/application.properties` combined with adding the `test` sources classpath to `bootRun` in Gradle should set those.  You'll also need to make sure you don't have a `src/main/resources/application.properties` because in that case the `test` one doesn't get picked up.

**Comment by xmlking** [comment]
it was in my project https://github.com/xmlking/micro-apps  (`gradle :apps:entity-service:bootRun`)
I took your example to add GCP logging to my sub-project.  the above setting seems working as expected now. 
👍🏽  Thanks for showcasing GCP integration example.

**Comment by jamesward** [comment]
Thanks!
